export default function Head() {
  return (
    <>
      <title>Europe&apos;s Refugee Crisis</title>
      {/* <meta content="width=device-width, initial-scale=1" name="viewport" /> */}
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo_black_bg.png" />
    </>
  );
}
